/* Generated by tools/fetch_photos.py — do not edit by hand.
 * To drop a photo, add its filename to excludePhotos in data.js;
 * that survives a re-run of the tool.
 */
TRIP.registerPhotos("quan-lan", [
  {
    "file": "p-1a9652af8a.jpg",
    "title": "Sơn Hào Beach, Cao Lôn Island, Vân Đồn, Quảng Ninh, Việt Nam",
    "author": "Phó Nháy",
    "license": "Public domain",
    "licenseUrl": "https://creativecommons.org/publicdomain/mark/1.0/",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:S%C6%A1n_H%C3%A0o_Beach,_Cao_L%C3%B4n_Island,_V%C3%A2n_%C4%90%E1%BB%93n,_Qu%E1%BA%A3ng_Ninh,_Vi%E1%BB%87t_Nam.jpg",
    "width": 900,
    "height": 675
  },
  {
    "file": "p-f2c8d49bef.jpg",
    "title": "Bai Tu Long Bay - Quang Ninh - Vietnam (35892945123)",
    "author": "AnhTuan Le",
    "license": "Public domain",
    "licenseUrl": "https://creativecommons.org/publicdomain/mark/1.0/",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Bai_Tu_Long_Bay_-_Quang_Ninh_-_Vietnam_(35892945123).jpg",
    "width": 900,
    "height": 519
  },
  {
    "file": "p-ff1a74abe1.jpg",
    "title": "Bai Tu Long Bay",
    "author": "NASA Earth Observatory images by Joshua Stevens, using Landsat data from the U.S. Geological Survey. Story by Kasha Patel.",
    "license": "Public domain",
    "licenseUrl": "https://creativecommons.org/publicdomain/mark/1.0/",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Bai_Tu_Long_Bay.jpeg",
    "width": 900,
    "height": 600
  },
  {
    "file": "p-ed8baba29b.jpg",
    "title": "Quan Lạn communal house",
    "author": "Phó Nháy",
    "license": "Public domain",
    "licenseUrl": "https://creativecommons.org/publicdomain/mark/1.0/",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Quan_L%E1%BA%A1n_communal_house.JPG",
    "width": 900,
    "height": 675
  },
  {
    "file": "p-b08886eae1.jpg",
    "title": "Quan Lan Island, Vân Đồn District",
    "author": "Original uploader was Viethavvh at vi.wikipedia",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Quan_Lan_Island,_V%C3%A2n_%C4%90%E1%BB%93n_District.jpg",
    "width": 900,
    "height": 675
  },
  {
    "file": "p-9c02d0ac35.jpg",
    "title": "Battle of Vân Đồn",
    "author": "Phó Nháy",
    "license": "Public domain",
    "licenseUrl": "https://creativecommons.org/publicdomain/mark/1.0/",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Battle_of_V%C3%A2n_%C4%90%E1%BB%93n.jpg",
    "width": 900,
    "height": 675
  },
  {
    "file": "p-a3069ee130.jpg",
    "title": "Bái Tử Long",
    "author": "Viethavvh at Vietnamese Wikipedia",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:B%C3%A1i_T%E1%BB%AD_Long.jpg",
    "width": 900,
    "height": 675
  },
  {
    "file": "p-c8e92ff581.jpg",
    "title": "Bái Tử Long sunset",
    "author": "Viethavvh at Vietnamese Wikipedia",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:B%C3%A1i_T%E1%BB%AD_Long_sunset.jpg",
    "width": 900,
    "height": 675
  }
]);
