/* Generated by tools/fetch_photos.py — do not edit by hand.
 * To drop a photo, add its filename to excludePhotos in data.js;
 * that survives a re-run of the tool.
 */
TRIP.registerPhotos("binh-lieu", [
  {
    "file": "p-2ab04aa052.jpg",
    "title": "BinhLieu by phone",
    "author": "NKSTTSSHNVN",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:BinhLieu_by_phone.jpg",
    "width": 900,
    "height": 506
  }
]);
