/* Generated by tools/fetch_photos.py — do not edit by hand.
 * To drop a photo, add its filename to excludePhotos in data.js;
 * that survives a re-run of the tool.
 */
TRIP.registerPhotos("ninh-binh", [
  {
    "file": "p-b21c2b019e.jpg",
    "title": "Cuc Phuong 01",
    "author": "Kien1980v (thảo luận)",
    "license": "Public domain",
    "licenseUrl": "https://creativecommons.org/publicdomain/mark/1.0/",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Cuc_Phuong_01.jpg",
    "width": 900,
    "height": 675
  },
  {
    "file": "p-067a7cb874.jpg",
    "title": "Tam Coc by Tuan Mai \"007\" (8888350545)",
    "author": "Tuan Mai",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Tam_Coc_by_Tuan_Mai_%22007%22_(8888350545).jpg",
    "width": 900,
    "height": 600
  },
  {
    "file": "p-065141a5e4.jpg",
    "title": "Trang An Landscape Complex, Ninh Binh Province, Vietnam, 20240202 1456 5313",
    "author": "Jakub Hałun",
    "license": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Trang_An_Landscape_Complex,_Ninh_Binh_Province,_Vietnam,_20240202_1456_5313.jpg",
    "width": 900,
    "height": 601
  },
  {
    "file": "p-f48d47b118.jpg",
    "title": "Trang An Landscape Complex, Ninh Binh Province, Vietnam, 20240202 1447 5310",
    "author": "Jakub Hałun",
    "license": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Trang_An_Landscape_Complex,_Ninh_Binh_Province,_Vietnam,_20240202_1447_5310.jpg",
    "width": 900,
    "height": 601
  },
  {
    "file": "p-757e171020.jpg",
    "title": "Goats in Ninh Hải, Ninh Binh province, Vietnam, 20240201 1521 4871",
    "author": "Jakub Hałun",
    "license": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Goats_in_Ninh_H%E1%BA%A3i,_Ninh_Binh_province,_Vietnam,_20240201_1521_4871.jpg",
    "width": 900,
    "height": 601
  },
  {
    "file": "p-a25b2c65d5.jpg",
    "title": "Trang An Landscape Complex, Ninh Binh Province, Vietnam, 20240202 1433 5283",
    "author": "Jakub Hałun",
    "license": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Trang_An_Landscape_Complex,_Ninh_Binh_Province,_Vietnam,_20240202_1433_5283.jpg",
    "width": 900,
    "height": 601
  },
  {
    "file": "p-ad48a254e1.jpg",
    "title": "Trang An Landscape Complex, Ninh Binh Province, Vietnam, 20240202 1403 5212",
    "author": "Jakub Hałun",
    "license": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Trang_An_Landscape_Complex,_Ninh_Binh_Province,_Vietnam,_20240202_1403_5212.jpg",
    "width": 900,
    "height": 601
  },
  {
    "file": "p-2561a27ba1.jpg",
    "title": "Trang An Landscape Complex, Ninh Binh Province, Vietnam, 20240202 1353 5165",
    "author": "Jakub Hałun",
    "license": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Trang_An_Landscape_Complex,_Ninh_Binh_Province,_Vietnam,_20240202_1353_5165.jpg",
    "width": 900,
    "height": 601
  }
]);
