/* Generated by tools/fetch_photos.py — do not edit by hand.
 * To drop a photo, add its filename to excludePhotos in data.js;
 * that survives a re-run of the tool.
 */
TRIP.registerPhotos("con-son-chi-linh", [
  {
    "file": "p-0cf48792d1.jpg",
    "title": "Den kiep bac",
    "author": "Handyhuy (thảo luận) 14:20, ngày 21 tháng 4 năm 2008 (UTC)",
    "license": "CC BY 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Den_kiep_bac.jpg",
    "width": 900,
    "height": 675
  },
  {
    "file": "p-ebc56695a3.jpg",
    "title": "Denthonguyentrai",
    "author": "Kien1980v (thảo luận)",
    "license": "Public domain",
    "licenseUrl": "https://creativecommons.org/publicdomain/mark/1.0/",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Denthonguyentrai.jpg",
    "width": 900,
    "height": 675
  }
]);
