/* Generated by tools/fetch_photos.py — do not edit by hand.
   To exclude a photo, add its filename to excludePhotos in data.js instead;
   that survives a re-run of the tool. */
TRIP.registerPhotos('template', []);
