/* Generated by tools/fetch_photos.py — do not edit by hand.
 * To drop a photo, add its filename to excludePhotos in data.js;
 * that survives a re-run of the tool.
 */
TRIP.registerPhotos("ho-dong-do", [
  {
    "file": "p-de26c8eae6.jpg",
    "title": "Đền Sóc - NKS",
    "author": "NKSTTSSHNVN",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:%C4%90%E1%BB%81n_S%C3%B3c_-_NKS.jpg",
    "width": 900,
    "height": 600
  },
  {
    "file": "p-9b6dc695ba.jpg",
    "title": "Núi Sóc 2 - NKS",
    "author": "NKSTTSSHNVN",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:N%C3%BAi_S%C3%B3c_2_-_NKS.jpg",
    "width": 900,
    "height": 600
  },
  {
    "file": "p-d6beea9318.jpg",
    "title": "Bình minh trên đỉnh núi Sóc - NKS",
    "author": "NKSTTSSHNVN",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:B%C3%ACnh_minh_tr%C3%AAn_%C4%91%E1%BB%89nh_n%C3%BAi_S%C3%B3c_-_NKS.jpg",
    "width": 900,
    "height": 600
  },
  {
    "file": "p-532b0f5e10.jpg",
    "title": "Núi Sóc mùa vàng - NKS",
    "author": "NKSTTSSHNVN",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:N%C3%BAi_S%C3%B3c_m%C3%B9a_v%C3%A0ng_-_NKS.jpg",
    "width": 900,
    "height": 600
  },
  {
    "file": "p-67b3c3c533.jpg",
    "title": "NewOne - Island House at Dong Do lake 2023",
    "author": "Newone",
    "license": "CC0",
    "licenseUrl": "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:NewOne_-_Island_House_at_Dong_Do_lake_2023.jpg",
    "width": 900,
    "height": 675
  },
  {
    "file": "p-1bf9ef4bf1.jpg",
    "title": "Núi Sóc",
    "author": "NKSTTSSHNVN",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:N%C3%BAi_S%C3%B3c.jpg",
    "width": 900,
    "height": 386
  },
  {
    "file": "p-50880de3c0.jpg",
    "title": "Đường về nhà - NKS",
    "author": "NKSTTSSHNVN",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:%C4%90%C6%B0%E1%BB%9Dng_v%E1%BB%81_nh%C3%A0_-_NKS.jpg",
    "width": 900,
    "height": 506
  },
  {
    "file": "p-aaf4733e99.jpg",
    "title": "DongQuan",
    "author": "NKSTTSSHNVN",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:DongQuan.jpg",
    "width": 900,
    "height": 600
  }
]);
