/* Generated by tools/fetch_photos.py — do not edit by hand.
 * To drop a photo, add its filename to excludePhotos in data.js;
 * that survives a re-run of the tool.
 */
TRIP.registerPhotos("dong-lam", [
  {
    "file": "p-1473f41fa8.jpg",
    "title": "Railways and Tramways of Việt Nam - Tonkin - Bắc Lệ, from Vola Family Photos of Indochina around 1880, railroad building to Lang Son (Collection Julie Vola, Flickr 50124447123)",
    "author": "Unknown photographer (Collection Julie Vola)",
    "license": "Public domain",
    "licenseUrl": "https://creativecommons.org/publicdomain/mark/1.0/",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Railways_and_Tramways_of_Vi%E1%BB%87t_Nam_-_Tonkin_-_B%E1%BA%AFc_L%E1%BB%87,_from_Vola_Family_Photos_of_Indochina_around_1880,_railroad_building_to_Lang_Son_(Collection_Julie_Vola,_Flickr_50124447123).jpg",
    "width": 900,
    "height": 603
  }
]);
