/* Generated by tools/fetch_photos.py — do not edit by hand.
 * To drop a photo, add its filename to excludePhotos in data.js;
 * that survives a re-run of the tool.
 */
TRIP.registerPhotos("cat-ba", [
  {
    "file": "p-69e981209e.jpg",
    "title": "Cat Ba national park",
    "author": "Binh Giang",
    "license": "Public domain",
    "licenseUrl": "https://creativecommons.org/publicdomain/mark/1.0/",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Cat_Ba_national_park.JPG",
    "width": 900,
    "height": 675
  },
  {
    "file": "p-32610f809f.jpg",
    "title": "Cat Ba town",
    "author": "Binh Giang",
    "license": "Public domain",
    "licenseUrl": "https://creativecommons.org/publicdomain/mark/1.0/",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Cat_Ba_town.JPG",
    "width": 900,
    "height": 675
  },
  {
    "file": "p-8f294630bb.jpg",
    "title": "Lan Ha Bay",
    "author": "Binh Giang",
    "license": "Public domain",
    "licenseUrl": "https://creativecommons.org/publicdomain/mark/1.0/",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Lan_Ha_Bay.JPG",
    "width": 900,
    "height": 675
  },
  {
    "file": "p-eed7a800d8.jpg",
    "title": "Cat Ba Island, Vietnam, 20240131 1431 4699",
    "author": "Jakub Hałun",
    "license": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Cat_Ba_Island,_Vietnam,_20240131_1431_4699.jpg",
    "width": 900,
    "height": 601
  },
  {
    "file": "p-a3be3d812e.jpg",
    "title": "Việt Hải, Cát Bà Island, Vietnam, 20240131 1211 4613",
    "author": "Jakub Hałun",
    "license": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Vi%E1%BB%87t_H%E1%BA%A3i,_C%C3%A1t_B%C3%A0_Island,_Vietnam,_20240131_1211_4613.jpg",
    "width": 900,
    "height": 601
  },
  {
    "file": "p-033f60b6af.jpg",
    "title": "Road to Việt Hải, Cát Bà Island, Vietnam, 20240131 1323 4619",
    "author": "Jakub Hałun",
    "license": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Road_to_Vi%E1%BB%87t_H%E1%BA%A3i,_C%C3%A1t_B%C3%A0_Island,_Vietnam,_20240131_1323_4619.jpg",
    "width": 900,
    "height": 601
  },
  {
    "file": "p-a6ad6f3144.jpg",
    "title": "Cat Ba Island, Vietnam, 20240131 1429 4692",
    "author": "Jakub Hałun",
    "license": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Cat_Ba_Island,_Vietnam,_20240131_1429_4692.jpg",
    "width": 900,
    "height": 508
  },
  {
    "file": "p-e4c5aeaadc.jpg",
    "title": "Cat Ba Island, Vietnam, 20240131 1431 4700",
    "author": "Jakub Hałun",
    "license": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Cat_Ba_Island,_Vietnam,_20240131_1431_4700.jpg",
    "width": 900,
    "height": 601
  }
]);
