/* Generated by tools/fetch_photos.py — do not edit by hand.
 * To drop a photo, add its filename to excludePhotos in data.js;
 * that survives a re-run of the tool.
 */
TRIP.registerPhotos("tam-dao", [
  {
    "file": "p-7a2ed2cb50.jpg",
    "title": "Vườn su su ở Tam Đảo",
    "author": "Bùi Thụy Đào Nguyên",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:V%C6%B0%E1%BB%9Dn_su_su_%E1%BB%9F_Tam_%C4%90%E1%BA%A3o.jpg",
    "width": 900,
    "height": 675
  },
  {
    "file": "p-d80b51ff03.jpg",
    "title": "Khu du lịch Tam Đảo",
    "author": "Viethavvh at vi.wikipedia",
    "license": "Public domain",
    "licenseUrl": "https://creativecommons.org/publicdomain/mark/1.0/",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Khu_du_l%E1%BB%8Bch_Tam_%C4%90%E1%BA%A3o.jpg",
    "width": 900,
    "height": 675
  },
  {
    "file": "p-ba38fb7e2b.jpg",
    "title": "Tam Đảo TT",
    "author": "NKSTTSSHNVN",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Tam_%C4%90%E1%BA%A3o_TT.jpg",
    "width": 900,
    "height": 600
  },
  {
    "file": "p-155f5e3df9.jpg",
    "title": "Thị trấn Tam Đảo - NKS",
    "author": "NKSTTSSHNVN",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Th%E1%BB%8B_tr%E1%BA%A5n_Tam_%C4%90%E1%BA%A3o_-_NKS.jpg",
    "width": 900,
    "height": 600
  },
  {
    "file": "p-4df28020de.jpg",
    "title": "Lâu đài Tam Đảo - NKS",
    "author": "NKSTTSSHNVN",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:L%C3%A2u_%C4%91%C3%A0i_Tam_%C4%90%E1%BA%A3o_-_NKS.jpg",
    "width": 900,
    "height": 600
  },
  {
    "file": "p-06480f0c50.jpg",
    "title": "Nhà Sáng tác Tam Đảo",
    "author": "Bùi Thụy Đào Nguyên",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Nh%C3%A0_S%C3%A1ng_t%C3%A1c_Tam_%C4%90%E1%BA%A3o.jpg",
    "width": 900,
    "height": 675
  },
  {
    "file": "p-159c8ef232.jpg",
    "title": "Chùa ở Tam Đảo (48463210417)",
    "author": "Sketyl none",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Ch%C3%B9a_%E1%BB%9F_Tam_%C4%90%E1%BA%A3o_(48463210417).jpg",
    "width": 900,
    "height": 521
  },
  {
    "file": "p-e47937853f.jpg",
    "title": "Guan Yin of Hoi Ha pagoda, Vinh Phuc province, 16th century AD, lacquered wood - Vietnam National Museum of Fine Arts - Hanoi, Vietnam - DSC04870",
    "author": "Daderot",
    "license": "CC0",
    "licenseUrl": "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Guan_Yin_of_Hoi_Ha_pagoda,_Vinh_Phuc_province,_16th_century_AD,_lacquered_wood_-_Vietnam_National_Museum_of_Fine_Arts_-_Hanoi,_Vietnam_-_DSC04870.JPG",
    "width": 900,
    "height": 602
  }
]);
