/* ===========================================================================
   locations/registry.js

   THE ONE PLACE TO REGISTER A LOCATION.

   To add a destination:
     1. copy locations/_template/  ->  locations/<your-id>/
     2. fill in data.js
     3. add '<your-id>' to LOCATION_IDS below

   That's it. No HTML, CSS or rendering code needs to change.

   ---------------------------------------------------------------------------
   Why document.write?

   This site has no build step and must also work when opened straight off the
   filesystem (file://), where fetch() and ES modules are both blocked by CORS.
   That leaves classic <script> tags. Listing them by hand would mean editing
   two HTML files every time a location is added, so instead this file writes
   them during parse — one list, one edit point.

   document.write during initial parse is well-defined: the scripts are
   inserted into the token stream and execute in order, before any script that
   follows in the document. Browsers only intervene against *cross-origin*
   parser-blocking writes; these are same-origin relative paths.
   =========================================================================== */
(function (TRIP) {
  'use strict';

  /* ---- add new location ids here, in any order ---------------------------- */
  TRIP.LOCATION_IDS = [
    'cat-ba',
    'con-son-chi-linh',
    'dong-lam',
    'binh-lieu',
    'ninh-binh',
    'quan-lan',
    'tam-dao',
    'ho-dong-do'
  ];
  /* ------------------------------------------------------------------------ */

  TRIP.locations = [];
  TRIP.photos = {};

  /** Called by locations/<id>/data.js */
  TRIP.registerLocation = function (loc) {
    if (!loc || !loc.id) {
      if (window.console) console.warn('[trip] registerLocation: missing id, ignored', loc);
      return;
    }
    TRIP.locations.push(loc);
  };

  /** Called by locations/<id>/photos.js — generated by tools/fetch_photos.py */
  TRIP.registerPhotos = function (id, list) {
    if (!id) return;
    TRIP.photos[id] = Array.isArray(list) ? list : [];
  };

  /**
   * Photos for a location, best first.
   *
   * Two sources, merged:
   *   loc.localPhotos  — added by hand in data.js. Your own shots, or anything
   *                      you have chosen and are entitled to publish. These
   *                      come FIRST, so a hand-picked image wins the hero slot
   *                      over anything the fetch tool found.
   *   TRIP.photos[id]  — generated by tools/fetch_photos.py into photos.js.
   *
   * excludePhotos drops files from either set by filename.
   *
   * Local photos exist because the tool can only ever find what is freely
   * licensed and happens to be online. For several of these places that is
   * nothing at all, and a photo you took yourself beats every one of them.
   */
  TRIP.photosFor = function (loc) {
    var local = (loc.localPhotos || []).map(function (p) {
      var copy = {};
      for (var k in p) if (Object.prototype.hasOwnProperty.call(p, k)) copy[k] = p[k];
      copy._local = true;
      return copy;
    });
    var fetched = TRIP.photos[loc.id] || [];
    var all = local.concat(fetched);

    var skip = loc.excludePhotos || [];
    if (!skip.length) return all;
    return all.filter(function (p) { return skip.indexOf(p.file) === -1; });
  };

  /* Write the per-location script tags. Namespace and register functions above
     are already defined, so the data files have somewhere to land. */
  var base = 'locations/';
  for (var i = 0; i < TRIP.LOCATION_IDS.length; i++) {
    var id = TRIP.LOCATION_IDS[i];
    document.write('<script src="' + base + id + '/data.js"><\/script>');
    document.write('<script src="' + base + id + '/photos.js"><\/script>');
  }
})(window.TRIP = window.TRIP || {});
